// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeWeave
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeWeave.484657cb-5297-4a7b-8009-6d2639569879";
        public const string Name = "CodeWeave";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
