// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeWeave
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodeWeaveString = "de94022d-cce2-425f-882c-ec1f9f9dfdc9";
        public static Guid CodeWeave = new Guid(CodeWeaveString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeWeave_CommandGroup = 0x0001;
        public const int CodeWeave_ViewCommandGroup = 0x0002;
        public const int CodeWeave_SubMenuGroup = 0x0003;
        public const int CodeWeave_ViewSubMenuGroup = 0x0004;
        public const int CodeWeave_MenuProjectGroup = 0x0005;
        public const int CodeWeave_ContextSolutionGroup = 0x0006;
        public const int CodeWeave_ContextProjectGroup = 0x0007;
        public const int CodeWeave_Menu = 0x0010;
        public const int CodeWeave_ViewMenu = 0x0020;
        public const int CommandCompletion = 0x0100;
        public const int CommandShowChatWindow = 0x0101;
        public const int CommandCompileCommands = 0x0102;
    }
}
